# Development profili — faqat lokal ishlatish uchun
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# Lokal dev uchun JWT secret (FAQAT dev uchun!)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
