spring.application.name=avloniy_muzeyi

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG

# JWT - Buni ham o'zgaruvchiga olgan ma'qul, lekin hozircha qolsa ham bo'ladi
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=86400000

# CORS - Bunga keyinroq qaytamiz (Vercel linkini qo'yishimiz kerak bo'ladi)
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}

supabase.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}
